"""add nullable True

Revision ID: 39a3664b90a0
Revises: 4b1a3fd1ea14
Create Date: 2026-02-16 16:09:41.805418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39a3664b90a0'
down_revision: Union[str, Sequence[str], None] = '4b1a3fd1ea14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'duration_s',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=True)
    op.alter_column('attempts', 'error_message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('attempts', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('feedbacks', 'next_tip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('feedbacks', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('recordings', 'size_bytes',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=True)
    
    op.execute("""
        INSERT INTO questions (category, question)
        VALUES
        ('自分紹介', '職歴を教えてください'),
        ('志望動機', '志望動機を教えてください'),
        ('志望動機', '同業他社ではなく、弊社を志望理由を教えてください')
    """)

    op.execute("""
        INSERT INTO avatars (personality_id)
        VALUES
        (1),
        (2),
        (3)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'size_bytes',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=False)
    op.alter_column('feedbacks', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('feedbacks', 'next_tip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('attempts', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('attempts', 'error_message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('attempts', 'duration_s',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=False)
    
    op.execute("""
        DELETE FROM questions
        WHERE id IN (1, 2, 3)
    """)

    op.execute("""
        DELETE FROM avatars
        WHERE id IN (1, 2, 3)
    """)
    # ### end Alembic commands ###
