"""add avatars attempts feedbacks transcripts (int unsigned)

Revision ID: 3a26002628d2
Revises: 6e55e4b0f3ed
Create Date: 2026-02-21 00:02:55.006940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a26002628d2'
down_revision: Union[str, Sequence[str], None] = '6e55e4b0f3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('personality_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.CHAR(length=64), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('question_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'created'"), nullable=False),
    sa.Column('duration_limit_s', mysql.SMALLINT(unsigned=True), server_default='90', nullable=False),
    sa.Column('duration_s', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('attempt_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('avatar_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('good_points', sa.Text(), nullable=False),
    sa.Column('improve_points', sa.Text(), nullable=False),
    sa.Column('next_tip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('transcripts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('attempt_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('text', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('feedbacks')
    op.drop_table('attempts')
    op.drop_table('avatars')
    # ### end Alembic commands ###
