"""カテゴリの質問追加

Revision ID: d17d1aaae3fe
Revises: 2350e31c724e
Create Date: 2026-02-26 16:15:32.136525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd17d1aaae3fe'
down_revision: Union[str, Sequence[str], None] = '2350e31c724e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('feedbacks', 'grade',
    #            existing_type=mysql.ENUM('A', 'B', 'C', collation='utf8mb4_unicode_ci'),
    #            nullable=False)

    # テストデータ
    op.execute("""
        INSERT INTO categories (id, name)
        VALUES
        (3, '自己PR'),
        (4, '強み/弱み'),
        (5, 'キャリアビジョン'),
        (6, '価値観'),
        (7, 'チームワーク'),
        (8, 'リーダーシップ'),
        (9, '課題解決力')
    """)

    op.execute("""
        INSERT INTO questions (id, category_id, question_text)
        VALUES
        (4, 2, '弊社のどのような点に魅力を感じましたか？'),
        (5, 3, '自己PRをしてください。'),
        (6, 3, 'あなたらしさがわかる具体的なエピソードを教えてください'),
        (7, 4, 'あなたの強みと弱みを教えてください'),
               
        (8, 5, '5年後、10年後のキャリアビジョンを教えてください。'),
        (9, 5, '将来どのような社会人になりたいと考えていますか？'),
        (10, 5, 'キャリアを築く上で大切にしていることは何ですか？'),
        (11, 5, '当社でどのように成長していきたいですか？'),

        -- 価値観
        (12, 6, 'あなたが仕事をする上で最も大切にしている価値観は何ですか？'),
        (13, 6, 'これまでの人生で影響を受けた出来事を教えてください。'),
        (14, 6, '意思決定をする際に重視するポイントは何ですか？'),
        (15, 6, 'あなたにとって成功とは何ですか？'),

        -- チームワーク
        (16, 7, 'チームで成果を出した経験を教えてください。'),
        (17, 7, 'チーム内で意見が対立した際、どのように対応しますか？'),
        (18, 7, 'あなたがチームに貢献できることは何ですか？'),
        (19, 7, '周囲と協力する上で意識していることは何ですか？'),

        -- リーダーシップ
        (20, 8, 'リーダーとして取り組んだ経験を教えてください。'),
        (21, 8, 'メンバーをまとめる際に意識していることは何ですか？'),
        (22, 8, '困難な状況でチームをどう導きますか？'),
        (23, 8, 'リーダーに必要な資質とは何だと思いますか？'),

        -- 課題解決力
        (24, 9, 'これまでに直面した課題とその解決方法を教えてください。'),
        (25, 9, '問題の原因をどのように分析しますか？'),
        (26, 9, '改善提案を行った経験があれば教えてください。'),
        (27, 9, '予期せぬトラブルへの対応経験を教えてください。')
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('feedbacks', 'grade',
    #            existing_type=mysql.ENUM('A', 'B', 'C', collation='utf8mb4_unicode_ci'),
    #            nullable=True)

    #　テストデータ削除
    op.execute("""
        DELETE FROM categories
        WHERE id IN (, )
    """)
    
    op.execute("""
        DELETE FROM questions
        WHERE id IN ()
    """)
    # ### end Alembic commands ###
